### ISSUE TITLE
Backbone 1.2.x can no longer be used in Browserify environment without jQuery

### ISSUE THREAD

**Issue by stebunovd** [jashkenas/backbone#3873]
My project is using Backbone as a dependency, but doesn't use jQuery. Everything worked fine with Backbone 1.1.2, but when I tried to upgrade to Backbone 1.2.x my build became broken:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'jquery' from '/Users/dvs/Dropbox/Code/cub/node_modules/backbone'
    at /Users/dvs/Dropbox/Code/cub/node_modules/resolve/lib/async.js:46:17
    at process (/Users/dvs/Dropbox/Code/cub/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/dvs/Dropbox/Code/cub/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/dvs/Dropbox/Code/cub/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/dvs/Dropbox/Code/cub/node_modules/resolve/lib/async.js:92:31)
    at /Users/dvs/Dropbox/Code/cub/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```
I'm using latest versions of browserify (12.0.1) and nodejs (5.0.0).
I tried all Backbone versions from 1.2.0 to 1.2.3, and all of them are not working with my build. Latest compatible version seems to be 1.1.2.

**Comment by stebunovd** [comment]
Solved the problem by passing exclude option to Browserify as described [here](https://github.com/jashkenas/backbone/wiki/Using-Backbone-without-jQuery#without-jquery). Apparently it wasn't needed for Backbone versions 1.1.x and older, but needed for 1.2.x. Thanks everyone for help.
