### ISSUE TITLE
When upgrade to 0.99, the console report an error: "_.pick is not a function"  

### ISSUE THREAD

**Issue by vicenrele** [jashkenas/backbone#2070]
Hello.
When upgrade to 0.99, the console report an error: "_.pick is not a function"  . Why?
Previous version: 0.9.1

Regards
